//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicObj
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        public string PaymentID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public byte OnSale { get; set; }
        public Nullable<double> Total { get; set; }
        public string Note { get; set; }
        public string ServiceVipID { get; set; }
        public string AccountName { get; set; }
    
        public virtual AccountUser AccountUser { get; set; }
        public virtual ServiceVip ServiceVip { get; set; }
    }
}
