//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicObj
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistAdmin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaylistAdmin()
        {
            this.PlaylistAdmin_Song = new HashSet<PlaylistAdmin_Song>();
            this.PlaylistAdminLikeds = new HashSet<PlaylistAdminLiked>();
            this.PlaylistAdminListeneds = new HashSet<PlaylistAdminListened>();
            this.Collections = new HashSet<Collection>();
        }
    
        public string PlaylistID { get; set; }
        public string PlaylistName { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Image { get; set; }
        public string AccountName { get; set; }
        public Nullable<bool> isPublic { get; set; }
    
        public virtual AccountAdmin AccountAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistAdmin_Song> PlaylistAdmin_Song { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistAdminLiked> PlaylistAdminLikeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistAdminListened> PlaylistAdminListeneds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection> Collections { get; set; }
    }
}
