//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicObj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song_Artist
    {
        public string ArtistID { get; set; }
        public string SongID { get; set; }
        public bool Own { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Song Song { get; set; }
    }
}
