//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicObj
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public long ViewID { get; set; }
        public int Views { get; set; }
        public string SongID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Song Song { get; set; }
    }
}
